### ISSUE TITLE
Error: Call to undefined function DiagnosticsExtended\Diagnostic\posix_getuid()

### ISSUE THREAD

**Issue by MichaIng** [Findus23/matomo-DiagnosticsExtended#1]
I just tested the app with current Matomo 4.3.0 and the system checks then fail with:
```
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | #8 {main}
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | #7 /var/www/matomo/index.php(25): require_once('...')
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | #6 /var/www/matomo/core/dispatch.php(32): Piwik\FrontController-&gt;dispatch()
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | #5 /var/www/matomo/core/FrontController.php(167): Piwik\FrontController-&gt;doDispatch()
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | #4 /var/www/matomo/core/FrontController.php(615): call_user_func_array()
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | #3 [internal function]: Piwik\Plugins\Installation\Controller-&gt;systemCheckPage()
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | #2 /var/www/matomo/plugins/Installation/Controller.php(494): Piwik\Plugins\Diagnostics\DiagnosticService-&gt;runDiagnostics()
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | #1 /var/www/matomo/plugins/Diagnostics/DiagnosticService.php(54): Piwik\Plugins\Diagnostics\DiagnosticService-&gt;run()
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | #0 /var/www/matomo/plugins/Diagnostics/DiagnosticService.php(68): Piwik\Plugins\DiagnosticsExtended\Diagnostic\PhpUserCheck-&gt;execute()
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | Stack trace:
ERROR | Piwik\FrontController | 2021-05-17 14:28:31 UTC | 48e3c | Uncaught exception: Error: Call to undefined function Piwik\Plugins\DiagnosticsExtended\Diagnostic\posix_getuid() in /var/www/matomo/plugins/DiagnosticsExtended/Diagnostic/PhpUserCheck.php:42
```
The widget throws the same error.

Used with PHP v8.0.5.

**Comment by Findus23** [comment]
Hi, are you using Windows by chance?

**Comment by MichaIng** [comment]
Hi, no it's GNU/Linux Debian (Bullseye). Apache2 webserver with PHP-FPM handler.

**Comment by Findus23** [comment]
Hi,

That's weird. I use Debian Bullseye too and it works for me (and I assumed that the posix_* functions were available by default on Linux).

I can also see the posix.so file as a part of php7.4-common (https://packages.debian.org/bullseye/amd64/php7.4-common/filelist) so maybe check if there is a line like `extension=posix.so` anywhere in your php config. (for me it is in /etc/php/7.4/cli/conf.d/20-posix.ini which is a symlink to /etc/php/7.4/mods-available/posix.ini)
It also seems to be working with the deb.sury.org PHP in /etc/php/8.0/mods-available/posix.ini


Of course I can fix the plugin anyway to skip the check if the function is missing. (This should be released in 0.1.6)

**Comment by MichaIng** [comment]
Ah lol, I should have guessed that this function is part of the POSIX module, which was disabled. Enabling it solves the issue. However, your fix is good as well to skip the check that uses it. It could also be replaced with a warning that the PHP module needs to be enabled or so, but fine for now 👍.

**Comment by MichaIng** [comment]
Btw, the URL check seems to be doubled now that it is included in the Matomo core, isn't it? Else, it could/should check for the HTTP response code in the first place, like it was changed here: https://github.com/matomo-org/matomo/issues/17559

So generally:
1. If HTTP response is 4xx, all is fine.
2. Else if content it `;` (PHP handles the file?), it's semi-public.
3. Else (or else if specific content known to be part of the plain config file). it's really pubic.

Or switching 2. and 3. so check for a specific known mandatory config file content to differentiate between public and semi-public, as I'm not sure whether the PHP-handled output will be `;` for sure.

**Comment by Findus23** [comment]
> It could also be replaced with a warning that the PHP module needs to be enabled or so, but fine for now +1.

I don't think Matomo needs that module, so I don't think we need a warning about it.

> Btw, the URL check seems to be doubled now that it is included in the Matomo core, isn't it? Else, it could/should check for the HTTP response code in the first place, like it was changed here: matomo-org/matomo#17559

Yes that part is now redundant, but I'll keep my version in for now as it might catch more cases (in which case we can improve the core check) and it also checks other files.

> if specific content known to be part of the plain config file

https://github.com/Findus23/matomo-DiagnosticsExtended/blob/b6b0636f45113901bab98c76c369a302b652f1c8/Diagnostic/URLCheck.php#L93-L95
I check for "salt" as every config.ini.php should contain that word.

**Comment by MichaIng** [comment]
> I don't think Matomo needs that module, so I don't think we need a warning about it.

Jep I meant a warning that the PHP user check is skipped because of the missing module, not that it's an issue in itself.

> it might catch more cases (in which case we can improve the core check) and it also checks other files.

It has the same false alarm when a custom 4xx handler is used that contains a `;` character, but I like the way it differentiates between public and semi-public. That could be definitely ported over to the core.
